//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.CustomerAccount = new HashSet<CustomerAccount>();
            this.NotaryAccount = new HashSet<NotaryAccount>();
            this.SystemAccount = new HashSet<SystemAccount>();
            this.UserTransaction = new HashSet<UserTransaction>();
        }
    
        public long Seq { get; set; }
        public int LU_BankSeq { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> LU_AccountTypeSeq { get; set; }
        public string IBAN { get; set; }
        public int StatusSeq { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual LU_AccountType LU_AccountType { get; set; }
        public virtual LU_Bank LU_Bank { get; set; }
        public virtual Message Message { get; set; }
        public virtual ICollection<CustomerAccount> CustomerAccount { get; set; }
        public virtual ICollection<NotaryAccount> NotaryAccount { get; set; }
        public virtual ICollection<SystemAccount> SystemAccount { get; set; }
        public virtual ICollection<UserTransaction> UserTransaction { get; set; }
    }
}
