//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAccount = new HashSet<CustomerAccount>();
            this.ProcessApproval = new HashSet<ProcessApproval>();
        }
    
        public long Seq { get; set; }
        public string IdentityNo { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public long MobilePhoneNumber { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> StatusSeq { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Sex Sex1 { get; set; }
        public virtual ICollection<CustomerAccount> CustomerAccount { get; set; }
        public virtual ICollection<ProcessApproval> ProcessApproval { get; set; }
    }
}
