//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Item
    {
        public LU_Item()
        {
            this.PaymentTransaction = new HashSet<PaymentTransaction>();
            this.Rate = new HashSet<Rate>();
        }
    
        public int Seq { get; set; }
        public string Name { get; set; }
        public string InsertedTime { get; set; }
        public Nullable<System.DateTime> InsertedBy { get; set; }
        public string UpdatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
    
        public virtual ICollection<PaymentTransaction> PaymentTransaction { get; set; }
        public virtual ICollection<Rate> Rate { get; set; }
    }
}
