//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Account = new HashSet<Account>();
            this.Customer = new HashSet<Customer>();
            this.Estate = new HashSet<Estate>();
            this.LU_AccountType = new HashSet<LU_AccountType>();
            this.LU_Bank = new HashSet<LU_Bank>();
            this.LU_EstateType = new HashSet<LU_EstateType>();
            this.Notary = new HashSet<Notary>();
            this.PaymentTransaction = new HashSet<PaymentTransaction>();
            this.ProcessApproval = new HashSet<ProcessApproval>();
            this.Rate = new HashSet<Rate>();
            this.User = new HashSet<User>();
            this.User1 = new HashSet<User>();
            this.Vehicle = new HashSet<Vehicle>();
        }
    
        public int Seq { get; set; }
        public string Message1 { get; set; }
        public string InsertedTime { get; set; }
        public Nullable<System.DateTime> InsertedBy { get; set; }
        public string UpdatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Estate> Estate { get; set; }
        public virtual ICollection<LU_AccountType> LU_AccountType { get; set; }
        public virtual ICollection<LU_Bank> LU_Bank { get; set; }
        public virtual ICollection<LU_EstateType> LU_EstateType { get; set; }
        public virtual ICollection<Notary> Notary { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransaction { get; set; }
        public virtual ICollection<ProcessApproval> ProcessApproval { get; set; }
        public virtual ICollection<Rate> Rate { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}
