//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notary
    {
        public Notary()
        {
            this.NotaryAccount = new HashSet<NotaryAccount>();
            this.User = new HashSet<User>();
        }
    
        public long Seq { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountySeq { get; set; }
        public Nullable<int> StatusSeq { get; set; }
        public Nullable<bool> isPublic { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual County County { get; set; }
        public virtual Message Message { get; set; }
        public virtual ICollection<NotaryAccount> NotaryAccount { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
