//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public long Seq { get; set; }
        public long UserSeq { get; set; }
        public Nullable<int> LU_RateTypeSeq { get; set; }
        public Nullable<int> LU_ItemSeq { get; set; }
        public int StatusSeq { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual LU_Item LU_Item { get; set; }
        public virtual LU_RateType LU_RateType { get; set; }
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
