//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sex
    {
        public Sex()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public byte Seq { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
