//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemXEntities : DbContext
    {
        public SystemXEntities()
            : base("name=SystemXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Audit> Audit { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<County> County { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerAccount> CustomerAccount { get; set; }
        public DbSet<Estate> Estate { get; set; }
        public DbSet<LU_AccountType> LU_AccountType { get; set; }
        public DbSet<LU_Bank> LU_Bank { get; set; }
        public DbSet<LU_EstateType> LU_EstateType { get; set; }
        public DbSet<LU_Item> LU_Item { get; set; }
        public DbSet<LU_OperationType> LU_OperationType { get; set; }
        public DbSet<LU_ProcessType> LU_ProcessType { get; set; }
        public DbSet<LU_RateType> LU_RateType { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Notary> Notary { get; set; }
        public DbSet<NotaryAccount> NotaryAccount { get; set; }
        public DbSet<PaymentTransaction> PaymentTransaction { get; set; }
        public DbSet<ProcessApproval> ProcessApproval { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Sex> Sex { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<SystemAccount> SystemAccount { get; set; }
        public DbSet<TransactionDetailBuyer> TransactionDetailBuyer { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserTransaction> UserTransaction { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
    }
}
