//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetailBuyer
    {
        public long Seq { get; set; }
        public string TransactionID { get; set; }
        public long BuyerId { get; set; }
        public long BuyerAccount { get; set; }
        public decimal BuyerRatio { get; set; }
        public decimal TotalMoney { get; set; }
        public int Status { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
    }
}
