//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PaymentTransaction = new HashSet<PaymentTransaction>();
            this.Rate = new HashSet<Rate>();
            this.UserTransaction = new HashSet<UserTransaction>();
        }
    
        public long Seq { get; set; }
        public string IdentityNo { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public long MobilePhoneNumber { get; set; }
        public Nullable<int> StatusSeq { get; set; }
        public Nullable<int> RoleSeq { get; set; }
        public Nullable<long> NotarySeq { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Message Message1 { get; set; }
        public virtual Notary Notary { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransaction { get; set; }
        public virtual ICollection<Rate> Rate { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserTransaction> UserTransaction { get; set; }
    }
}
