//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public long Seq { get; set; }
        public long UserSeq { get; set; }
        public Nullable<long> UserAccountSeq { get; set; }
        public decimal TotalMoney { get; set; }
        public Nullable<long> NotaryAccountSeq { get; set; }
        public Nullable<int> LU_OperationTypeSeq { get; set; }
        public decimal TotalMoneyToSystem { get; set; }
        public int StatusSeq { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual LU_OperationType LU_OperationType { get; set; }
        public virtual NotaryAccount NotaryAccount { get; set; }
        public virtual User User { get; set; }
    }
}
