//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public long Seq { get; set; }
        public string RuhsatNo { get; set; }
        public string SaseNo { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int DateOfInTrafic { get; set; }
        public string Color { get; set; }
        public long Kilometer { get; set; }
        public int StatusSeq { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Message Message { get; set; }
    }
}
